### ISSUE TITLE
interview-jingdong.md存在笔误

### ISSUE THREAD

**Issue by Janlei-CN** [crisxuan/bestJavaer#2]
"JDK 动态代理和 GClib 动态代理、JDK 动态代理具体实现原理、CGLib 动态代理、两者对比。"
其中应该是CGlib。

**Comment by crisxuan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Janlei-CN"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 上午7:54
收件人:&nbsp;"crisxuan/bestJavaer"<bestJavaer@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[crisxuan/bestJavaer] interview-jingdong.md存在笔误 (#2)





 
"JDK 动态代理和 GClib 动态代理、JDK 动态代理具体实现原理、CGLib 动态代理、两者对比。"
 其中应该是CGlib。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.




感谢提出 PR，马上修复

**Comment by crisxuan** [comment]
感谢提出，已修复
